### ISSUE TITLE
Checking if a string starts/ends with another string

### ISSUE THREAD

**Issue by Night-walker** [daokoder/dao#342]
This common string operation lacks a dedicated method in Dao. There are ways to emulate it, for instance as `str[: %prefix - 1] == prefix` or `str.match(suffix + '$') != none`, but there isn't one which would be simple, efficient and universal at the same time.

I suppose such operation should finally have better support in the language. I does not have to be in the form of `startsWith()`/`endsWith()` -- I'm considering a variant like
```ruby
has(self: string, ...: tuple<enum<prefix,suffix,infix,circumfix>, string>) => bool
```
For example
```ruby
str.has(prefix = '(', suffix = ')')
str.has(infix = '=') # e.g., 'key = value', but not '= value' or 'key ='
str.has(circumfix = '"') # e.g., "literal"
```

**Comment by daokoder** [comment]
I also have encounter a number of occasions when I really wanted such method. Now let's add one:)

I had only thought about supporting prefix/suffix, by a method like
~~~
align( self: string, other: string, where: enum<prefix,suffix> ) => int
~~~
which returns the max length of common prefix/suffix.

> ~~~
has(self: string, ...: tuple<enum<prefix,suffix,infix,circumfix>, string>) => bool
~~~

This looks like an interesting alternative (though, I would remove `circumfix`, since it is a special case for using both `prefix` and `suffix`, and it's a rare word). But I feel it could be more flexible to obtain the length of the common prefix/suffix as in `align()`.

**Comment by Night-walker** [comment]
`align` would be less suitable for checking string boundaries:
```ruby
text.align(keyword, $prefix) == %keyword
```
comparing to
```ruby
text.has(prefix = keyword)
```
and even
```ruby
text[: %keyword - 1] = keyword
```
`has` is also better when a literal is used -- just one occurrence to edit if it's to be changed. As for seeking the largest common suffix/prefix -- not sure; never had a need to.

**Comment by dumblob** [comment]
I also have hard time finding a good example where the largest common suffix/prefix is the optimal solution.

**Comment by daokoder** [comment]
> align would be less suitable for checking string boundaries:

True, but I feel `has` may be a bit limited in functionality. How about something like:
~~~
contain( self: string, ...: tuple<pos:int,keyword:string> ) => bool
~~~
which will check a list of keywords at specific locations, and negative locations means searching backward from the end. So you can use it like:
~~~
text.contain( (0, keyword) )  # prefix;
text.contain( (-1, keyword) )  # suffix;
text.contain( (0, keyword1), (-1, keyword2) )  # prefix and suffix;
text.contain( (1, key1), (12, key2), (33, key3) )  # arbitrary;
~~~
To be compatible with `has`, something like the following can do:
~~~
contain( self: string, ...: tuple<pos:int|enum<prefix,suffix,infix>,keyword:string> ) => bool
~~~

> I also have hard time finding a good example where the largest common suffix/prefix is the optimal solution.

Right, searching full keywords is more common.

**Comment by dumblob** [comment]
> `contain( self: string, ...: tuple<pos:int|enum<prefix,suffix,infix>,keyword:string> ) => bool`

This suits me.

**Comment by Night-walker** [comment]
Me too.

**Comment by daokoder** [comment]
> `str.has(infix = '=') # e.g., 'key = value', but not '= value' or 'key ='`

I think `infix` should not be supported, because it introduces inconsistency, or unnecessary overhead to ensure consistency. Here, `infix` requires no occurrence in the prefix and suffix, which is inconsistent with `prefix/suffix` checking that says nothing about if they can occur in other parts of a string. If we remove the that requirement from `infix` checking, it would become ambiguous and probably useless. Or, if we enforce similar requirement on `prefix/suffix` checking, there would be some overhead which should be unnecessary for most use cases. Even worse, it introduces logic problem: for `s="key"`, should `s.contain(prefix="key")` be true or false? Because it is both the prefix and suffix, that none other occurrence requirement cannot be applied without logic dilemma. (Of course, if we insist prefix must be *pre* something, there will be no dilemma, but I believe it will become less useful, and inconsistent with integer parameters for the method).

**Comment by Night-walker** [comment]
OK, prefix and suffix should be sufficient.

**Comment by Night-walker** [comment]
BTW, `contains` looks more natural.

**Comment by daokoder** [comment]
> BTW, contains looks more natural.

Yes, more natural for english speaking people. But I am not very convinced that we should start to use verb conjugations (right term for this?) in method names, because it may become confusing which methods to use and which not to use them.

**Comment by daokoder** [comment]
BTW, the method is supported now.

**Comment by Night-walker** [comment]
> But I am not very convinced that we should start to use verb conjugations (right term for this?) in method names, because it may become confusing which methods to use and which not to use them.

It's very simple: bool methods which tests certain properties of an object. This is how such thing are usually named virtually everywhere as far as I can recall. Well, Ruby obviously uses `?`-ending instead, but otherwise it is the generally adopted notation. On the contrary, `contain` is actually a verb, which is much more confusing.

I already named methods like this across the modules, and there meaning seems definitely clearer that way.

**Comment by daokoder** [comment]
Now `string.contain()` is changed to `string.contains()`.

**Comment by Night-walker** [comment]
OK, done.
