### ISSUE TITLE
Optimizing locking around string sharing

### ISSUE THREAD

**Issue by Night-walker** [daokoder/dao#349]
First of all, freeing data in `DString_DeleteData()` can be performed after exiting the critical section. That would be better then making a syscall while global lock is held.

Then, allocating memory and copying data during detaching can also be performed without locking: it should be safe to refer to string data as (if I get it correctly) it cannot be changed from a concurrent thread at least until `data[0] -= 1;` is executed. It could look like this:
```c
...
#ifdef DAO_WITH_THREAD
	DMutex_Lock( & mutex_string_sharing );
#endif
	if( data[0] >1 || data == dao_string ){
#ifdef DAO_WITH_THREAD
		DMutex_Unlock( & mutex_string_sharing );
#endif
		if( bufsize < self->size ) bufsize = self->size;
		self->bufSize = bufsize + 1;
		data2 = (int*) dao_malloc( (self->bufSize + 1)*sizeof(char) + sizeof(int) );
		data2[0] = 1;
		memcpy( data2+1, data+1, (self->size + 1)*sizeof(char) );
		self->chars = (char*)(data2 + 1);
#ifdef DAO_WITH_THREAD
		DMutex_Lock( & mutex_string_sharing );
#endif
		if ( data[0] > 1 )
			data[0] -= 1;
		else 
			dao_free( data );
	}
#ifdef DAO_WITH_THREAD
	DMutex_Unlock( & mutex_string_sharing );
#endif
...
```

**Comment by daokoder** [comment]
Something can be indeed improved for string locking. But I think the code you show here is incorrect, because the condition (`data[0]`) checking and modification do not happen in the same locking period. So if a string data is shared by exactly two strings, and these two strings are being detached at the same time, your code will unfortunately detach both, where only one of them should be detached. But it can be fixed easily.

**Comment by Night-walker** [comment]
> your code will unfortunately detach both

I know, that's why I delete `data` if that happens. I think such possibility is unlikely comparing to a queue of threads waiting for lengthy detaching, which is worse.

**Comment by Night-walker** [comment]
Feasible improvements were made. Fixed.
